### PR TITLE
Kd first branch

### PR DESCRIPTION
**Pull request by ghost**
Adding API and updating .gitignore.

### CODE REVIEW

**Comment by Josh-Webb** [comment]
👍

**Comment by Josh-Webb** [comment]
Is this a review???

**Comment by Josh-Webb** [comment]
Approve.

**Review by Josh-Webb — APPROVED** [review]
🥇

**Review by dek-haji — APPROVED** [review]

**Comment by ghost** [comment]
NEW MASTER!

**Pull request merged**
